src/LaerlingProject/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LaerlingProject.Data;
using Microsoft.AspNetCore.Mvc;
using LaerlingProject.Models.JobViewModels;
using LaerlingProject.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LaerlingProject.Models;

namespace LaerlingProject.Controllers
{
    public class JobsController : Controller
    {
        private IJobRepository _jobRepo;
        private UserManager<ApplicationUser> _userManager; 

        public JobsController(IJobRepository jobRepo, UserManager<ApplicationUser> userManager)
        {
            _jobRepo = jobRepo;
            _userManager = userManager; 
        }

        // GET: /Index/
        [HttpGet]
        public IActionResult Index(JobsMessageId? message = null)
        {
            ViewData["Message"] =
                message == JobsMessageId.NotAWorkerError ? "Du skal registrer dig som arbejder for at søge jobs."
                : "";

            return View(); 
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Info(int id)
        {
            var user = await GetCurrentUserAsync(); 

            if (user.LaerlingProfilID == null)
            {
                return RedirectToAction(nameof(Index), new { Message = JobsMessageId.NotAWorkerError }); 
            }
    

            var job = _jobRepo.GetJob(id); 

            return View(job); 
        }




        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        public enum JobsMessageId
        {
            NotAWorkerError, 
        }

    }
}

src/LaerlingProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaerlingProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link href="https://fonts.googleapis.com/css?family=Roboto|Yanone+Kaffeesatz" rel="stylesheet">


</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LaerlingProject</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>*@

    <div class="navbar navbar-inverse navbar-fixed-top custom-navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle toggle-custom" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="brand">
                    <a asp-area="" asp-controller="Home" asp-action="Index" style="color: #fff; text-decoration: none">
                        <h2>ReadyToWork</h2>
                    </a>
                    
                </div>
            </div>
            <div class="navbar-collapse collapse border-color">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Forside</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Find arbejder</a></li>
                    <li><a asp-area="" asp-controller="Jobs" asp-action="Index">Find job</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="body-content" style="padding-top: 25px">
        @RenderBody()
        <hr />
        <footer>
            <div class="container">
                <p>&copy; 2017 - LaerlingProject</p>
            </div>
           
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <environment>
        <link rel="stylesheet" href="~/lib/bootstrap-select/dist/css/bootstrap-select.min.css">
        <script src="~/lib/bootstrap-select/js/i18n/defaults-da_DK.js"></script>
        <script src="~/lib/bootstrap-select/js/bootstrap-select.js"></script>
    </environment>

    <environment>
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" />
        <script src="~/lib/select2/dist/js/select2.min.js"></script>
    </environment>
    @*<environment>
            <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
            <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
        </environment>*@

    @RenderSection("scripts", required: false)
</body>
</html>